timestamp = 2023-10-25T19:30:47Z
github = { repo = "input-output-hk/cardano-ledger", rev = "f4269490502fc928c13a86e71c059d88cb5ac995" }
subdir = 'libs/cardano-ledger-binary'

[[revisions]]
number = 1
timestamp = 2024-12-11T19:54:53Z

[[revisions]]
number = 2
timestamp = 2025-09-10T20:25:33Z

[[revisions]]
number = 3
timestamp = 2026-02-19T00:52:30Z
