timestamp = 2025-03-21T09:06:59Z
github = { repo = "intersectmbo/cardano-ledger", rev = "a9e78ae63cf8870f0ce6ce76bd7029b82ddb47e1" }
subdir = 'libs/cardano-ledger-binary'

[[revisions]]
number = 1
timestamp = 2025-05-15T10:30:42Z

[[revisions]]
number = 2
timestamp = 2025-09-10T20:23:36Z

[[revisions]]
number = 3
timestamp = 2026-02-05T12:53:54Z
