timestamp = 2023-11-30T09:59:24Z
github = { repo = "input-output-hk/fs-sim", rev = "0b66f2f7181482b4de541e3acb43e384e512ad91" }
subdir = 'fs-sim'

[[revisions]]
number = 1
timestamp = 2024-02-23T09:48:23Z

[[revisions]]
number = 2
timestamp = 2024-06-06T15:28:08Z

[[revisions]]
number = 3
timestamp = 2024-07-15T00:42:50Z

[[revisions]]
number = 4
timestamp = 2024-07-15T05:04:54Z
