timestamp = 2025-09-10T02:05:10Z
github = { repo = "IntersectMBO/cardano-ledger", rev = "faa7a9dc347697b11d4da5b7818b1731e11aeeef" }
subdir = 'libs/cardano-ledger-binary'

[[revisions]]
number = 1
timestamp = 2025-09-10T20:31:08Z

[[revisions]]
number = 2
timestamp = 2025-12-24T01:24:22Z
