timestamp = 2025-09-30T09:14:27Z
github = { repo = "IntersectMBO/ouroboros-consensus", rev = "4759da500fc9e1d25f2d91c865aa41054cc70f22" }
subdir = 'ouroboros-consensus-diffusion'

[[revisions]]
number = 1
timestamp = 2026-02-06T12:03:28Z
