timestamp = 2025-05-14T06:57:37Z
github = { repo = "intersectmbo/ouroboros-network", rev = "1eafe7bc742da1709fc98c62c48c519bbce503c0" }
subdir = 'ouroboros-network-framework'

[[revisions]]
number = 1
timestamp = 2026-01-05T11:07:19Z
