timestamp = 2023-03-10T07:05:55Z
github = { repo = "input-output-hk/plutus-apps", rev = "c4f4dc5fedd5b1804781abb7db0fb5a553e24ecb" }
subdir = 'plutus-ledger'

[[revisions]]
  number = 1
  timestamp = 2023-03-13T07:04:28+00:00

[[revisions]]
  number = 2
  timestamp = 2023-03-14T03:15:21+00:00
