timestamp = 2025-08-27T16:03:37Z
github = { repo = "intersectmbo/ouroboros-network", rev = "cb806d0875f7278440d8ecb86bb210402670d8e5" }
subdir = 'quickcheck-monoids'

[[revisions]]
number = 1
timestamp = 2026-02-12T05:22:35Z
