timestamp = 2025-01-13T22:30:16Z
github = { repo = "IntersectMBO/cardano-prelude/", rev = "68e015f6e7f17e67d8dbf16bc1590b926d064962" }
subdir = 'cardano-prelude'

[[revisions]]
number = 1
timestamp = 2025-09-29T23:47:47Z

[[revisions]]
number = 2
timestamp = 2026-02-20T01:29:02Z
