timestamp = 2023-06-08T18:20:50Z
github = { repo = "input-output-hk/cardano-ledger", rev = "eae43793dc80533fe7f3fc02b76303e7df7d001f" }
subdir = 'libs/cardano-ledger-binary'

[[revisions]]
number = 1
timestamp = 2024-12-11T19:54:36Z

[[revisions]]
number = 2
timestamp = 2025-09-10T20:25:44Z

[[revisions]]
number = 3
timestamp = 2026-02-19T00:52:30Z
