timestamp = 2024-07-02T02:47:44Z
github = { repo = "IntersectMBO/cardano-ledger", rev = "698a24c1b5064468ef614532a6524dce2b41d7f5" }
subdir = 'libs/cardano-ledger-core'

[[revisions]]
number = 1
timestamp = 2024-12-12T00:23:02Z

[[revisions]]
number = 2
timestamp = 2025-05-13T19:30:32Z

[[revisions]]
number = 3
timestamp = 2026-02-19T00:52:30Z
