timestamp = 2025-06-03T08:30:50Z
github = { repo = "intersectmbo/ouroboros-network", rev = "879683d42157ba68de3e4a1498a5c76228fa0a5a" }
subdir = 'ouroboros-network-framework'

[[revisions]]
number = 1
timestamp = 2025-06-19T23:32:17Z

[[revisions]]
number = 2
timestamp = 2025-06-20T04:57:28Z

[[revisions]]
number = 3
timestamp = 2026-01-05T11:06:54Z
