timestamp = 2024-05-07T20:34:03Z
github = { repo = "intersectmbo/ouroboros-network", rev = "c5314093f33c01f910be59b24f092be8ceeff9b1" }
subdir = 'quickcheck-monoids'

[[revisions]]
number = 1
timestamp = 2024-07-15T23:33:18Z
