timestamp = 2022-11-11T00:24:50Z
github = { repo = "input-output-hk/cardano-ledger", rev = "2fac95ef338ff9622543d08fe16d0fa6716d0019" }
subdir = 'eras/byron/crypto'

[[revisions]]
number = 1
timestamp = 2023-03-21T14:33:01Z

[[revisions]]
number = 2
timestamp = 2024-09-02T21:57:21Z
