timestamp = 2026-01-23T20:19:31Z
github = { repo = "IntersectMBO/ouroboros-consensus", rev = "025ab689811dbf05583f41107f47347e597ce68b" }
subdir = 'ouroboros-consensus-cardano'

[[revisions]]
number = 1
timestamp = 2026-01-29T19:27:06Z
