timestamp = 2023-02-23T15:33:46Z
github = { repo = "input-output-hk/cardano-ledger", rev = "2f5956038233e4df0a065d96db32398605603f9b" }
subdir = 'libs/cardano-ledger-core'

[[revisions]]
number = 1
timestamp = 2024-01-25T14:10:44Z

[[revisions]]
number = 2
timestamp = 2024-12-12T00:23:01Z
