timestamp = 2023-11-30T09:59:24Z
github = { repo = "input-output-hk/fs-sim", rev = "0b66f2f7181482b4de541e3acb43e384e512ad91" }
subdir = 'fs-api'

[[revisions]]
number = 1
timestamp = 2024-02-23T10:34:09Z

[[revisions]]
number = 2
timestamp = 2024-06-06T15:27:49Z

[[revisions]]
number = 3
timestamp = 2024-07-15T00:43:41Z
