timestamp = 2026-01-23T20:19:10Z
github = { repo = "IntersectMBO/ouroboros-consensus", rev = "025ab689811dbf05583f41107f47347e597ce68b" }
subdir = 'ouroboros-consensus-diffusion'

[[revisions]]
number = 1
timestamp = 2026-01-29T19:27:06Z

[[revisions]]
number = 2
timestamp = 2026-02-06T11:04:14Z
