timestamp = 2023-04-26T17:24:56Z
github = { repo = "input-output-hk/cardano-ledger", rev = "55a58ad476a978a24d56e8ce28b5f4bbaa159169" }
subdir = 'libs/cardano-ledger-binary'

[[revisions]]
number = 1
timestamp = 2024-12-11T19:54:29Z
