timestamp = 2023-05-16T08:11:15Z
github = { repo = "input-output-hk/typed-protocols", rev = "071fed3c912a15fe4d86cd33db160eab40707857" }
subdir = 'typed-protocols-cborg'

[[revisions]]
number = 1
timestamp = 2023-11-08T10:10:42Z

[[revisions]]
number = 2
timestamp = 2024-07-05T05:05:48Z
