timestamp = 2025-09-10T02:05:10Z
github = { repo = "IntersectMBO/cardano-ledger", rev = "faa7a9dc347697b11d4da5b7818b1731e11aeeef" }
subdir = 'libs/cardano-ledger-core'

[[revisions]]
number = 1
timestamp = 2025-10-01T14:54:47Z

[[revisions]]
number = 2
timestamp = 2026-02-19T00:52:30Z
