timestamp = 2026-02-03T13:03:55Z
github = { repo = "IntersectMBO/cardano-base", rev = "58a3814c049324578a1cbc7f8ab9e0edae42249a" }
subdir = 'cardano-binary'

[[deprecations]]
timestamp = 2026-02-07T05:22:03Z
deprecated = true
