timestamp = 2023-11-14T12:07:29Z
github = { repo = "input-output-hk/cardano-ledger", rev = "f85ec6f2e0a80101009187f79ff154ab33a82a21" }
subdir = 'libs/cardano-ledger-binary'

[[revisions]]
number = 1
timestamp = 2024-12-11T19:54:56Z

[[revisions]]
number = 2
timestamp = 2025-09-10T20:25:30Z

[[revisions]]
number = 3
timestamp = 2026-02-19T00:52:30Z
