timestamp = 2023-07-20T22:17:39Z
github = { repo = "input-output-hk/cardano-ledger", rev = "fb85fbeedffe60258612e39cd786ce1cdc87fc9c" }
subdir = 'libs/cardano-ledger-core'

[[revisions]]
number = 1
timestamp = 2024-01-25T14:10:44Z

[[revisions]]
number = 2
timestamp = 2024-12-12T00:23:02Z
