timestamp = 2024-09-23T21:46:49Z
github = { repo = "IntersectMBO/cardano-ledger", rev = "052d07325dcc4bf8a004bcad2c58d7fc7ce65d92" }
subdir = 'libs/cardano-ledger-core'

[[revisions]]
number = 1
timestamp = 2024-12-12T00:23:02Z

[[revisions]]
number = 2
timestamp = 2025-05-13T19:30:47Z

[[revisions]]
number = 3
timestamp = 2026-02-19T00:52:30Z
