timestamp = 2024-08-20T20:11:43Z
github = { repo = "intersectmbo/cardano-ledger", rev = "068c7a6ff43b154219fb73834f7f0c6ee7d752b1" }
subdir = 'libs/cardano-ledger-binary'

[[revisions]]
number = 1
timestamp = 2024-12-11T19:55:11Z

[[revisions]]
number = 2
timestamp = 2025-05-15T10:30:42Z

[[revisions]]
number = 3
timestamp = 2025-09-10T20:25:15Z

[[revisions]]
number = 4
timestamp = 2026-02-19T00:52:30Z
