timestamp = 2025-09-30T09:14:27Z
github = { repo = "IntersectMBO/ouroboros-consensus", rev = "4759da500fc9e1d25f2d91c865aa41054cc70f22" }
subdir = 'ouroboros-consensus-protocol'

[[revisions]]
number = 1
timestamp = 2026-01-23T08:47:59Z
