timestamp = 2025-08-23T15:05:21Z
github = { repo = "intersectmbo/cardano-base", rev = "971708b0142f86507e8694351186551ac8753cf0" }
subdir = 'cardano-crypto-tests'

[[revisions]]
number = 1
timestamp = 2025-09-16T18:21:39Z

[[revisions]]
number = 2
timestamp = 2025-12-23T22:10:03Z
