timestamp = 2024-01-23T08:57:37Z
github = { repo = "intersectmbo/ouroboros-network", rev = "5618742c1e15ed1256fc62794eec7560040d8c0a" }
subdir = 'monoidal-synchronisation'

[[revisions]]
number = 1
timestamp = 2024-07-15T22:57:14Z
