timestamp = 2023-06-08T18:20:50Z
github = { repo = "input-output-hk/cardano-ledger", rev = "eae43793dc80533fe7f3fc02b76303e7df7d001f" }
subdir = 'libs/cardano-ledger-core'

[[revisions]]
number = 1
timestamp = 2024-01-25T14:10:44Z

[[revisions]]
number = 2
timestamp = 2024-12-12T00:23:02Z
