timestamp = 2024-01-26T10:34:07Z
github = { repo = "IntersectMBO/cardano-ledger", rev = "6e2d37cc0f47bd02e89b4ce9f78b59c35c958e96" }
subdir = 'libs/cardano-ledger-binary'

[[revisions]]
number = 1
timestamp = 2024-12-11T19:57:09Z

[[revisions]]
number = 2
timestamp = 2025-09-10T20:25:27Z

[[revisions]]
number = 3
timestamp = 2026-02-19T00:52:30Z
