timestamp = 2023-07-05T12:27:25Z
github = { repo = "input-output-hk/cardano-ledger", rev = "9b3a09485f1ba14ce8dc267d5596f85116ce5330" }
subdir = 'libs/cardano-ledger-core'

[[revisions]]
number = 1
timestamp = 2024-01-25T14:10:44Z

[[revisions]]
number = 2
timestamp = 2024-12-12T00:23:02Z
