timestamp = 2026-01-27T17:54:50Z
github = { repo = "IntersectMBO/cardano-api", rev = "8f860b1969da893e9020ce28fbd455f883cadec5" }
subdir = 'cardano-api'

[[revisions]]
number = 1
timestamp = 2026-01-29T01:19:14Z

[[revisions]]
number = 2
timestamp = 2026-01-30T03:40:53Z
