timestamp = 2023-04-05T21:13:03Z
github = { repo = "input-output-hk/cardano-ledger", rev = "f10f06f6ab96b5ee52a28ccc45b41a592efde4b7" }
subdir = 'libs/cardano-ledger-core'

[[revisions]]
number = 1
timestamp = 2024-01-25T14:10:44Z

[[revisions]]
number = 2
timestamp = 2024-12-12T00:23:01Z
