timestamp = 2025-03-21T09:06:59Z
github = { repo = "intersectmbo/cardano-ledger", rev = "a9e78ae63cf8870f0ce6ce76bd7029b82ddb47e1" }
subdir = 'libs/cardano-ledger-core'

[[revisions]]
number = 1
timestamp = 2025-05-13T19:30:58Z

[[revisions]]
number = 2
timestamp = 2025-10-01T14:54:47Z

[[revisions]]
number = 3
timestamp = 2026-02-19T00:52:30Z
