timestamp = 2024-03-29T00:54:16Z
github = { repo = "input-output-hk/cardano-ledger", rev = "ed6d38b0bf0a54504c781b3c274745846476ca3c" }
subdir = 'libs/cardano-ledger-binary'

[[revisions]]
number = 1
timestamp = 2024-12-11T19:55:03Z

[[revisions]]
number = 2
timestamp = 2025-09-10T20:25:24Z

[[revisions]]
number = 3
timestamp = 2026-02-19T00:52:30Z
